/**
 * RIFT — Catalogue des talents permanents
 * Points gagnés : 1 par run terminé (mort ou victoire).
 * Les talents s'appliquent à chaque run dès le départ.
 */

export const TALENT_CATALOG = [
  // ── Offensif ────────────────────────────────────────────────────────────────
  {
    id:       'tranchant',
    name:     'Lame Acérée',
    icon:     '⚔',
    cost:     4,
    category: 'offense',
    desc:     '+1 ATQ au départ de chaque run.',
    statBonus: { stat: 'attack', value: 1 },
  },
  {
    id:       'precision',
    name:     'Précision',
    icon:     '🎯',
    cost:     8,
    category: 'offense',
    desc:     'Chaque run démarre avec 1 stack de Critique gratuit.',
    passive:  'free_critique',
  },

  // ── Défensif ─────────────────────────────────────────────────────────────────
  {
    id:       'vigueur',
    name:     'Vigueur',
    icon:     '❤',
    cost:     4,
    category: 'defense',
    desc:     '+5 PV max au départ de chaque run.',
    statBonus: { stat: 'maxHp', value: 5 },
  },
  {
    id:       'armure',
    name:     'Armure',
    icon:     '🛡',
    cost:     4,
    category: 'defense',
    desc:     '+1 DEF au départ de chaque run.',
    statBonus: { stat: 'defense', value: 1 },
  },
  {
    id:       'constitution',
    name:     'Constitution',
    icon:     '💪',
    cost:     8,
    category: 'defense',
    desc:     '+10 PV max au départ de chaque run.',
    requires: 'vigueur',
    statBonus: { stat: 'maxHp', value: 10 },
  },
  {
    id:           'resilience',
    name:         'Résilience',
    icon:         '🌿',
    cost:         8,
    category:     'defense',
    desc:         'Soigne 2 PV après chaque salle terminée.',
    passive:      'room_regen',
    passiveValue: 2,
  },

  // ── Utilitaire ───────────────────────────────────────────────────────────────
  {
    id:           'collecteur',
    name:         'Collecteur',
    icon:         '💎',
    cost:         4,
    category:     'utility',
    desc:         'Commence chaque run avec 3 fragments.',
    passive:      'start_fragments',
    passiveValue: 3,
  },
  {
    id:           'richesse',
    name:         'Richesse',
    icon:         '💰',
    cost:         8,
    category:     'utility',
    desc:         'Commence chaque run avec 8 fragments.',
    requires:     'collecteur',
    passive:      'start_fragments',
    passiveValue: 8,
  },
  {
    id:       'maestro',
    name:     'Maestro',
    icon:     '✨',
    cost:     12,
    category: 'utility',
    desc:     'Commence chaque run avec 1 upgrade aléatoire.',
    passive:  'start_upgrade',
  },

  // ── Survie ───────────────────────────────────────────────────────────────────
  {
    id:       'endurance',
    name:     'Endurance',
    icon:     '🩹',
    cost:     8,
    category: 'defense',
    desc:     '+8 PV max au départ. Nécessite Vigueur.',
    requires: 'vigueur',
    statBonus: { stat: 'maxHp', value: 8 },
  },
  {
    id:       'bouclier_initial',
    name:     'Garde Permanente',
    icon:     '🔵',
    cost:     12,
    category: 'defense',
    desc:     'Commence chaque salle de combat avec un bouclier actif.',
    requires: 'armure',
    passive:  'start_shield',
  },

  // ── Nouveaux talents (10) ───────────────────────────────────────────────────
  {
    id:       'fureur',
    name:     'Fureur',
    icon:     '🔥',
    cost:     4,
    category: 'offense',
    desc:     '+1 ATQ au départ de chaque run.',
    statBonus: { stat: 'attack', value: 1 },
  },
  {
    id:       'duelliste',
    name:     'Duelliste',
    icon:     '🥇',
    cost:     8,
    category: 'offense',
    desc:     'Commence chaque run avec un stack de Critique gratuit supplémentaire.',
    passive:  'free_critique',
  },
  {
    id:       'execution',
    name:     'Exécution',
    icon:     '🗡',
    cost:     12,
    category: 'offense',
    desc:     '+2 ATQ au départ de chaque run. Nécessite Lame Acérée.',
    requires: 'tranchant',
    statBonus: { stat: 'attack', value: 2 },
  },
  {
    id:       'carapace',
    name:     'Carapace',
    icon:     '🐚',
    cost:     4,
    category: 'defense',
    desc:     '+1 DEF au départ de chaque run.',
    statBonus: { stat: 'defense', value: 1 },
  },
  {
    id:       'rempart',
    name:     'Rempart',
    icon:     '🧱',
    cost:     12,
    category: 'defense',
    desc:     'Commence chaque salle de combat avec un bouclier actif. Nécessite Armure.',
    requires: 'armure',
    passive:  'start_shield',
  },
  {
    id:       'vigueur_solaire',
    name:     'Vigueur Solaire',
    icon:     '☀',
    cost:     8,
    category: 'defense',
    desc:     '+8 PV max au départ de chaque run.',
    statBonus: { stat: 'maxHp', value: 8 },
  },
  {
    id:       'butin',
    name:     'Butin',
    icon:     '🪙',
    cost:     4,
    category: 'utility',
    desc:     '+4 fragments de départ.',
    statBonus: { stat: 'fragments', value: 4 },
  },
  {
    id:       'trouvailles',
    name:     'Trouvailles',
    icon:     '🧭',
    cost:     8,
    category: 'utility',
    desc:     'Commence chaque run avec 6 fragments. Nécessite Collecteur.',
    requires: 'collecteur',
    passive:  'start_fragments',
    passiveValue: 6,
  },
  {
    id:       'oracle',
    name:     'Oracle',
    icon:     '🔮',
    cost:     12,
    category: 'utility',
    desc:     'Commence chaque run avec 1 upgrade aléatoire. Nécessite Maestro.',
    requires: 'maestro',
    passive:  'start_upgrade',
  },
  {
    id:       'surplus',
    name:     'Surplus',
    icon:     '📦',
    cost:     8,
    category: 'utility',
    desc:     '+8 fragments de départ.',
    statBonus: { stat: 'fragments', value: 8 },
  },
];

export function getTalentById(id) {
  return TALENT_CATALOG.find(t => t.id === id) || null;
}
